nrepo: &nrepo
  image: plugins/docker
  secrets: [ docker_username, docker_password ]

prod: &prod
  <<: *nrepo
  tags: [ latest, "1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}" ]
  when:
    branch: master

pipeline:
  app-proxy: &app-proxy
    <<: *prod
    context: containers/app-proxy
    dockerfile: containers/app-proxy/Dockerfile
    repo: nativecode/app-proxy

  pihole: &pihole
    <<: *prod
    context: containers/pihole
    dockerfile: containers/pihole/Dockerfile
    repo: nativecode/pihole

  radarr: &radarr
    <<: *prod
    context: containers/radarr
    dockerfile: containers/radarr/Dockerfile
    repo: nativecode/radarr

  sonarr: &sonarr
    <<: *prod
    context: containers/sonarr
    dockerfile: containers/sonarr/Dockerfile
    repo: nativecode/sonarr

  notification:
    image: plugins/slack
    channel: builds
    username: drone
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
