latest: &latest
  registry: up.nrepo.io
  secrets:
    - source: nrepo_username
      target: docker_username
    - source: nrepo_password
      target: docker_password
  tags: [ "1.${DRONE_BUILD_NUMBER}-pre", "latest" ]
  when:
    branch: develop

stable: &stable
  registry: docker.io
  secrets: [ docker_username, docker_password ]
  tags: [ "1.${DRONE_BUILD_NUMBER}", "latest", "stable" ]
  when:
    branch: master

slack: &slack
  channel: builds
  username: drone
  secrets:
    - source: webhook_slack_builds
      target: plugin_webhook

appauth: &appauth
  context: containers/appauth
  dockerfile: containers/appauth/Dockerfile

mntnfs: &mntnfs
  context: containers/mntnfs
  dockerfile: containers/mntnfs/Dockerfile

pihole: &pihole
  context: containers/pihole
  dockerfile: containers/pihole/Dockerfile

plex: &plex
  context: containers/plex
  dockerfile: containers/plex/Dockerfile

radarr: &radarr
  context: containers/radarr
  dockerfile: containers/radarr/Dockerfile

sonarr: &sonarr
  context: containers/sonarr
  dockerfile: containers/sonarr/Dockerfile

wordpress: &wordpress
  context: containers/wordpress
  dockerfile: containers/wordpress/Dockerfile

pipeline:
  # appauth
  appauth_latest:
    image: plugins/docker
    repo: up.nrepo.io/appauth
    <<: [ *appauth, *latest ]
  appauth_stable:
    image: plugins/docker
    repo: nativecode/appauth
    <<: [ *appauth, *stable ]
  # mntnfs
  mntnfs_latest:
    image: plugins/docker
    repo: up.nrepo.io/mntnfs
    <<: [ *mntnfs, *latest ]
  mntnfs_stable:
    image: plugins/docker
    repo: nativecode/mntnfs
    <<: [ *mntnfs, *stable ]
  # pihole
  pihole_latest:
    image: plugins/docker
    repo: up.nrepo.io/pihole
    <<: [ *pihole, *latest ]
  pihole_stable:
    image: plugins/docker
    repo: nativecode/pihole
    <<: [ *pihole, *stable ]
  # plex
  plex_latest:
    image: plugins/docker
    repo: up.nrepo.io/plex
    <<: [ *plex, *latest ]
  plex_stable:
    image: plugins/docker
    repo: nativecode/plex
    <<: [ *plex, *stable ]
  # radarr
  radarr_latest:
    image: plugins/docker
    repo: up.nrepo.io/radarr
    <<: [ *radarr, *latest ]
  radarr_stable:
    image: plugins/docker
    repo: nativecode/radarr
    <<: [ *radarr, *stable ]
  # sonarr
  sonarr_latest:
    image: plugins/docker
    repo: up.nrepo.io/sonarr
    <<: [ *sonarr, *latest ]
  sonarr_stable:
    image: plugins/docker
    repo: nativecode/sonarr
    <<: [ *sonarr, *stable ]
  # wordpress
  wordpress_latest:
    image: plugins/docker
    repo: up.nrepo.io/wordpress
    <<: [ *wordpress, *latest ]
  wordpress_stable:
    image: plugins/docker
    repo: nativecode/wordpress
    <<: [ *wordpress, *stable ]
  # notifications
  notification:
    image: plugins/slack
    when:
      status: [ success, failure ]
    <<: *slack
