latest: &latest
  registry: push.nrepo.io
  tags: [ "1.1-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}", "latest" ]
  when:
    branch: [ develop, master ]

stable: &stable
  registry: docker.io
  secrets: [ docker_username, docker_password ]
  tags: [ "1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}", "stable" ]
  when:
    branch: master

slack: &slack
  channel: builds
  username: drone
  secrets:
    - source: webhook_slack_builds
      target: plugin_webhook

appauth: &appauth
  context: containers/appauth
  dockerfile: containers/appauth/Dockerfile

pihole: &pihole
  context: containers/pihole
  dockerfile: containers/pihole/Dockerfile

radarr: &radarr
  context: containers/radarr
  dockerfile: containers/radarr/Dockerfile

sonarr: &sonarr
  context: containers/sonarr
  dockerfile: containers/sonarr/Dockerfile

pipeline:
  appauth_latest:
    image: plugins/docker
    secrets: [ nrepo_username, nrepo_password ]
    repo: push.nrepo.io/appauth
    <<: [ *appauth, *latest ]

  appauth_stable:
    image: plugins/docker
    repo: nativecode/appauth
    <<: [ *appauth, *stable ]

  pihole_latest:
    image: plugins/docker
    repo: push.nrepo.io/pihole
    <<: [ *pihole, *latest ]

  pihole_stable:
    image: plugins/docker
    repo: nativecode/pihole
    <<: [ *pihole, *stable ]

  radarr_latest:
    image: plugins/docker
    repo: push.nrepo.io/radarr
    <<: [ *radarr, *latest ]

  radarr_stable:
    image: plugins/docker
    repo: nativecode/radarr
    <<: [ *radarr, *stable ]

  sonarr_latest:
    image: plugins/docker
    repo: push.nrepo.io/sonarr
    <<: [ *sonarr, *latest ]

  sonarr_stable:
    image: plugins/docker
    repo: nativecode/sonarr
    <<: [ *sonarr, *stable ]

  notification: &notification
    image: plugins/slack
    when:
      status: [ success, failure ]
    <<: *slack
