latest: &latest
  secrets: [ nrepo_username, nrepo_password ]
  tags: [ "latest", "1.1-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}" ]
  when:
    branch: [ develop, master ]

stable: &stable
  secrets: [ docker_username, docker_password ]
  tags: [ "stable", "1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}" ]
  when:
    branch: master

slack: &slack
  channel: builds
  username: drone
  secrets:
    - source: webhook_slack_builds
      target: plugin_webhook

appauth: &appauth
  context: containers/appauth
  dockerfile: containers/appauth/Dockerfile

pihole: &pihole
  context: containers/pihole
  dockerfile: containers/pihole/Dockerfile

radarr: &radarr
  context: containers/radarr
  dockerfile: containers/radarr/Dockerfile

sonarr: &sonarr
  context: containers/sonarr
  dockerfile: containers/sonarr/Dockerfile

pipeline:
  appauth_latest:
    image: plugins/docker
    repo: nrepo.io/appauth
    <<: [ *appauth, *latest ]

  appauth_stable:
    image: plugins/docker
    repo: nativecode/appauth
    <<: [ *appauth, *stable ]

  notification: &notification
    image: plugins/slack
    when:
      status: [ success, failure ]
    <<: *slack
