latest: &latest
  registry: up.nrepo.io
  secrets:
    - source: nrepo_username
      target: docker_username
    - source: nrepo_password
      target: docker_password
  tags: [ "1.${DRONE_BUILD_NUMBER}-pre", "latest" ]
  when:
    branch: master

stable: &stable
  registry: docker.io
  secrets: [ docker_username, docker_password ]
  tags: [ "1.${DRONE_BUILD_NUMBER}", "stable", "stable-1" ]
  when:
    event: tag
    branch: master

slack: &slack
  channel: builds
  username: drone
  secrets:
    - source: webhook_slack_builds
      target: plugin_webhook

appauth: &appauth
  context: containers/appauth
  dockerfile: containers/appauth/Dockerfile

pihole: &pihole
  context: containers/pihole
  dockerfile: containers/pihole/Dockerfile

radarr: &radarr
  context: containers/radarr
  dockerfile: containers/radarr/Dockerfile

sonarr: &sonarr
  context: containers/sonarr
  dockerfile: containers/sonarr/Dockerfile

pipeline:
  # appauth
  appauth_latest:
    image: plugins/docker
    repo: up.nrepo.io/appauth
    <<: [ *appauth, *latest ]
  appauth_stable:
    image: plugins/docker
    repo: nativecode/appauth
    <<: [ *appauth, *stable ]
  # pihole
  pihole_latest:
    image: plugins/docker
    repo: up.nrepo.io/pihole
    <<: [ *pihole, *latest ]
  pihole_stable:
    image: plugins/docker
    repo: nativecode/pihole
    <<: [ *pihole, *stable ]
  # radarr
  radarr_latest:
    image: plugins/docker
    repo: up.nrepo.io/radarr
    <<: [ *radarr, *latest ]
  radarr_stable:
    image: plugins/docker
    repo: nativecode/radarr
    <<: [ *radarr, *stable ]
  # sonarr
  sonarr_latest:
    image: plugins/docker
    repo: up.nrepo.io/sonarr
    <<: [ *sonarr, *latest ]
  sonarr_stable:
    image: plugins/docker
    repo: nativecode/sonarr
    <<: [ *sonarr, *stable ]
  # notifications
  notification:
    image: plugins/slack
    when:
      status: [ success, failure ]
    <<: *slack
