nrepo: &nrepo
  image: plugins/docker
  secrets: [ docker_username, docker_password ]

prod: &prod
  <<: *nrepo
  tags: [ latest, "1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}" ]
  when:
    branch: master

pipeline:
  app-proxy: &app-proxy
    <<: *prod
    context: containers/app-proxy
    dockerfile: containers/app-proxy/Dockerfile
    repo: app-proxy

  pihole: &pihole
    <<: *prod
    context: containers/pihole
    dockerfile: containers/pihole/Dockerfile
    repo: pihole

  radarr: &radarr
    <<: *prod
    context: containers/radarr
    dockerfile: containers/radarr/Dockerfile
    repo: radarr

  sonarr: &sonarr
    <<: *prod
    context: containers/sonarr
    dockerfile: containers/sonarr/Dockerfile
    repo: sonarr
