nrepo: &nrepo
  image: plugins/docker
  secrets: [ docker_username, docker_password ]

prod: &prod
  <<: *nrepo
  tags: [ latest, "1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}" ]
  when:
    branch: master

slack: &slack
  image: plugins/slack
  channel: builds
  username: drone
  secrets:
    - source: webhook_slack_builds
      target: plugin_webhook

pipeline:
  release_app-proxy: &release_app-proxy
    <<: *prod
    context: containers/app-proxy
    dockerfile: containers/app-proxy/Dockerfile
    repo: nativecode/app-proxy

  release_pihole: &release_pihole
    <<: *prod
    context: containers/pihole
    dockerfile: containers/pihole/Dockerfile
    repo: nativecode/pihole

  release_radarr: &release_radarr
    <<: *prod
    context: containers/radarr
    dockerfile: containers/radarr/Dockerfile
    repo: nativecode/radarr

  release_sonarr: &release_sonarr
    <<: *prod
    context: containers/sonarr
    dockerfile: containers/sonarr/Dockerfile
    repo: nativecode/sonarr

  notification: &notification
    <<: *slack
    when:
      status: [ success, failure ]
